# Generated by Django 5.2.1 on 2025-07-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreMetric',
            fields=[
                ('metric_id', models.AutoField(primary_key=True, serialize=False)),
                ('metric_type', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period', models.CharField(max_length=10)),
                ('recorded_at', models.DateTimeField()),
            ],
        ),
    ]
