# Generated by Django 5.2.1 on 2025-07-25 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubcategories',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productsubcategories',
            name='product',
        ),
        migrations.RemoveField(
            model_name='category',
            name='kind',
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='products.category'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='products_ca_parent__f3c24e_idx'),
        ),
        migrations.DeleteModel(
            name='ProductSubcategories',
        ),
    ]
